### ISSUE TITLE
Pretty weak

### ISSUE THREAD

**Issue by lua-51** [OwlUniversal/Roblox-Asset-Logger#1]
Well I think you might need improvements to this project! Or just direct people to asset central it's quite better out there!

**Comment by OwlUniversal** [comment]
let people rewrite it if its "Pretty weak"

**Comment by Gonistical** [comment]
coded in python, inaccurate

**Comment by lua-51** [comment]
> let people rewrite it if its "Pretty weak"

I'm about to blow up your mind. Would you believe me if it was already done before you by asset central and it went more successful than your stupid reincarnation! That's right I had to tell you that!

**Comment by Gonistical** [comment]
![image](https://github.com/OwlUniversal/Roblox-Asset-Logger/assets/165362601/3242d2c0-e2a0-479f-ae36-8efe229a6308)
